language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build

after_failure: cat $TRAVIS_BUILD_DIR/common/build/outputs/lint-results-debug.xml

# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
