language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24

script: ./gradlew build

# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
